{% set cf_version = "1.5.6" %}
{% set cf_hash = "90f235d8d8c1abeef4fd142234e15869d532a1deae98c28ad1f0ba75ed41e826" %}
{% set af_version = "2.3.7" %}
{% set af_hash = "3bf28af2e1c5866f5f5bcffea9f540b7cbf53939c71f19ceb4775d6ec4d3032a" %}

package:
  name: colabfold
  version: {{ cf_version }}

build:
  noarch: python
  script: |
    python -m pip install --no-deps --ignore-installed colabfold/
    python -m pip install --no-deps --ignore-installed alphafold/
  run_exports:
    - {{ pin_subpackage('colabfold', max_pin="x") }}
  number: 2

source:
  - url: https://github.com/ntnn19/ColabFold/archive/refs/tags/v{{ cf_version }}.tar.gz
    sha256: {{ cf_hash }}
    folder: colabfold
  - url: https://github.com/ntnn19/alphafold/archive/refs/tags/v{{ af_version }}.tar.gz
    sha256: {{ af_hash }}
    folder: alphafold

requirements:
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - python
    - absl-py
    - matplotlib-base
    - numpy
    - scipy
    - requests
    - tqdm
    - pandas
    - appdirs
    - py3Dmol
    - dm-tree
    - ml-collections
    - importlib-metadata
    - dm-haiku >=0.0.12
    - biopython ==1.79
    - jax >=0.4.23,<0.4.26
    - jaxlib >=0.4.23,<0.4.26
    - tensorflow-base >=2.12.1=cpu*
    - mmseqs2 >=15.6f452
    - kalign2 >=2.04
    - hhsuite >=3.3.0
    - openmm >=7.7.0,<8.1.0
    - pdbfixer

test:
  commands:
    - which colabfold_batch

about:
  home: https://github.com/ntnn19/ColabFold
  summary: "ColabFold: making protein folding accessible to all"
  license: MIT

extra:
  identifiers:
    - doi:10.1038/s41592-022-01488-1
    - biotools:colabfold
  recipe-maintainers:
    - milot-mirdita
